# Note: Replace your-dockerhub-username/imdb-top-movies:latest with the actual Docker image name you push to your registry.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdb-top-movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imdb-top-movies
  template:
    metadata:
      labels:
        app: imdb-top-movies
    spec:
      containers:
      - name: imdb-top-movies
        image: your-dockerhub-username/imdb-top-movies:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: imdb-top-movies-service
spec:
  selector:
    app: imdb-top-movies
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
